# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36865940ab04af592c61622fd8ceba89ac132efdae6eeb5c3704861753c0fc726570fe07c7f9dc0c529bb126f5729c42b014bcb3cc5a80aa0a4875a0f2fce007

test:
  secret_key_base: f57fb452b376072b203bb5df0613ca81b1d12a2681282bb3e957a356211b09a7a0d116d58bf749df427d0a3cf35fea777a34083dd96631f464ce2a0f1b2e37ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
